---
- name: ensure apt cache is updated
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: ensure python3 is present
  ansible.builtin.package:
    name:
      - python3
      - python3-pip

- name: ensure pydocker is installed
  ansible.builtin.package:
    name:
      - python3-docker
